name: daily-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl ${{ secrets.ACCESS_TOKEN }} https://lc-notion.vercel.app/api/update
