name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Call our API route
        run: |
          curl ${{ secrets.ACCESS_TOKEN }} https://lc-notion.vercel.app/api/update